typography_spectrum: 0.18268340965732932
color:
  brandStrength: 0.8889651221688837
  lightness: 0.03136512963101268
  saturation: 0.6078832601197064
  rhythmicContrast: 0.07851185160689056
  brandColors:
    - '#D7D0CC'
    - '#AAA2C3'
    - '#EFDFEF'
    - '#B9B1D5'
    - '#FFFFFF'
github: true
layout_spectrum: 0.729175811400637
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a76bb72-fda7-4240-a584-a4467358d6a1.png
name: Outside In - Business Consultants
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Home
    id: b17ce829-39f3-431b-b52c-03cad655025d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5cfef591-a871-445e-96b4-27fc1c427f10.png
title: Outside In Business Consultants
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/080df31b-eaf7-4efe-a4d5-020cdf930de3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/080df31b-eaf7-4efe-a4d5-020cdf930de3.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Pointing Business Owners Towards Success Through Business Systems for
  Excellence
purpose:
  - type: contact
    url: 'mailto:info@2outsidein.com'
    label: Contact us
